name = "space-impact-lb"
main = "worker.js"
compatibility_date = "2024-10-01"

# Replace <KV_ID> with the id printed by:
#   wrangler kv namespace create LB
[[kv_namespaces]]
binding = "LB"
id = "b3c9a38f4e3d444a9db43a6f98b25bb0"
